services:
  mongo:
    image: mongo:8
    container_name: lab-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: labuser
      MONGO_INITDB_ROOT_PASSWORD: labpass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./rsc/init.js:/docker-entrypoint-initdb.d/init.js:ro

volumes:
  mongo_data:
